import { TaskItem, Client, HabitItem } from '@/types';
import { getTodayString, getDaysOffset } from './utils';

// Retained sample datasets for optional "Load Sample Data" demonstration
export const SAMPLE_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'Sarah Chen',
    company: 'Apex Innovations',
    email: 'sarah@apexinnovations.io',
    phone: '+1 (555) 342-9182',
    status: 'active',
    rate: '$150/hr',
    totalBudget: '$24,000',
    color: '#6366F1',
    notes: 'Q3 Enterprise Design System revamp and mobile onboarding overhaul.',
    createdAt: getDaysOffset(-20),
  },
  {
    id: 'client-2',
    name: 'Marcus Vance',
    company: 'Nova Retail Brands',
    email: 'm.vance@novabrands.co',
    phone: '+1 (555) 782-4410',
    status: 'active',
    rate: '$5,000/mo retainer',
    totalBudget: '$30,000',
    color: '#F59E0B',
    notes: 'E-commerce platform migration and headless Shopify frontend architecture.',
    createdAt: getDaysOffset(-15),
  },
  {
    id: 'client-3',
    name: 'Elena Rostova',
    company: 'Stellar Health Tech',
    email: 'elena@stellarhealth.org',
    phone: '+1 (555) 901-2245',
    status: 'lead',
    rate: '$135/hr',
    totalBudget: '$15,000',
    color: '#10B981',
    notes: 'Telehealth patient portal compliance audit and accessibility uplift.',
    createdAt: getDaysOffset(-5),
  },
];

export const SAMPLE_TASKS: TaskItem[] = [
  {
    id: 's-t-1',
    title: 'Annual preventative health checkup',
    description: 'Appointment at St. Jude Health Pavilion. Bring medical requisition forms.',
    workspace: 'personal',
    status: 'todo',
    priority: 'high',
    dueDate: getTodayString(),
    dueTime: '09:30',
    tags: ['Health'],
    isEvent: true,
    eventDurationMinutes: 60,
    createdAt: getTodayString(),
  },
  {
    id: 's-t-2',
    title: 'Review Q3 P&L Statement with Accountant',
    description: 'Analyze quarterly revenue and tax deductions.',
    workspace: 'business',
    status: 'todo',
    priority: 'urgent',
    dueDate: getTodayString(),
    dueTime: '14:00',
    tags: ['Finance', 'Taxes'],
    isEvent: true,
    createdAt: getTodayString(),
  },
  {
    id: 's-t-3',
    title: 'Apex Innovations: Deliver Final Mobile UX',
    description: 'Deliver responsive prototype and component specs.',
    workspace: 'client',
    clientId: 'client-1',
    clientName: 'Apex Innovations',
    status: 'in_progress',
    priority: 'urgent',
    dueDate: getDaysOffset(1),
    tags: ['Design', 'Milestone'],
    createdAt: getTodayString(),
  },
];

export const SAMPLE_HABITS: HabitItem[] = [
  {
    id: 's-h-1',
    title: 'Morning 90-min Deep Work Block',
    workspace: 'business',
    category: 'Productivity',
    frequency: 'daily',
    targetDaysPerWeek: 6,
    completedDates: [getDaysOffset(-1), getTodayString()],
    streak: 2,
    createdAt: getDaysOffset(-10),
  },
  {
    id: 's-h-2',
    title: 'Workout & 30-min Cardio / Mobility',
    workspace: 'personal',
    category: 'Health',
    frequency: 'daily',
    targetDaysPerWeek: 5,
    completedDates: [getTodayString()],
    streak: 1,
    createdAt: getDaysOffset(-10),
  },
];
